#cloud-config

coreos:
  units:
    - name: zookeeper.service
      command: start
      content: |
        [Unit]
        Description=Zookeeper
        Author=David Asabina <david@supr.nu>
        After=docker.service
    
        [Service]
        Restart=always
        ExecStartPre=-/usr/bin/docker kill zookeeper
        ExecStartPre=-/usr/bin/docker rm zookeeper
        ExecStartPre=/usr/bin/docker pull garland/zookeeper
        ExecStart=/usr/bin/docker run --name zookeeper -p 2181:2181 -p 2888:2888 -p 3888:3888 garland/zookeeper
    - name: mesos-master.service
      command: start
      content: |
        [Unit]
        Description=Mesos Master
        Author=David Asabina <david@supr.nu>
        After=zookeeper.service
  
        [Service]
        Restart=always
        ExecStartPre=-/usr/bin/docker kill mesos-master
        ExecStartPre=-/usr/bin/docker rm mesos-master
        ExecStartPre=/usr/bin/docker pull garland/mesosphere-docker-mesos-master
        ExecStart=/usr/bin/docker run --name mesos-master --net="host" -p 5050:5050 -e "MESOS_HOSTNAME=$private_ipv4" -e "MESOS_IP=$private_ipv4" -e "MESOS_ZK=zk://$private_ipv4:2181/mesos" -e "MESOS_PORT=5050" -e "MESOS_LOG_DIR=/var/log/mesos" -e "MESOS_QUORUM=1" -e "MESOS_REGISTRY=in_memory" -e "MESOS_WORK_DIR=/var/lib/mesos" garland/mesosphere-docker-mesos-master
    - name: marathon.service
      command: start
      content: |
        [Unit]
        Description=Marathon
        Author=David Asabina <david@supr.nu>
        After=mesos-master.service
  
        [Service]
        Restart=always
        ExecStartPre=-/usr/bin/docker kill marathon
        ExecStartPre=-/usr/bin/docker rm marathon
        ExecStartPre=/usr/bin/docker pull garland/mesosphere-docker-marathon
        ExecStart=/usr/bin/docker run --name marathon -p 8080:8080 garland/mesosphere-docker-marathon --master zk://$private_ipv4:2181/mesos --zk zk://$private_ipv4:2181/marathon
        ExecStop=/usr/bin/docker rm marathon
    - name: mesos-slave.service
      command: start
      content: |
        [Unit]
        Description=Mesos Slave
        Author=David Asabina <david@supr.nu>
        After=marathon.service
  
        [Service]
        Restart=always
        ExecStart=/usr/bin/docker run --name mesos-slave -v "/var/run/docker.sock:/var/run/docker.sock" -e "MESOS_MASTER=zk://$private_ipv4:2181/mesos" -e "MESOS_LOG_DIR=/var/log/mesos" -e "MESOS_LOGGING_LEVEL=INFO" suprnovae/mesos-muscle:experimental
        ExecStop=/usr/bin/docker rm mesos-slave
write_files:
  - path: /etc/sudoers.d/waagent
    content: |
      yoda ALL = (ALL) NOPASSWD: ALL
